import president from "../Images/Rectangle 204.png";
export const doctors = [
  {
    image: president,
    designation: "President",
    name: "Dr. L.G. Jadhav",
    place: "Mumbai",
    mobile: "9969026062",
    state: "Maharashtra",
  },
  {
    image: president,
    designation: "Gen. Secretry",
    name: "Dr. Anil Bajare",
    place: "Amravati",
    mobile: "9969026062",
    state: "Maharashtra",
  },
  {
    image: president,
    designation: "Treasurer",
    name: "Dr. Sanjay Bhakkad",
    place: "Nanded",
    mobile: "9890631051",
    state: "Maharashtra",
  },
  {
    image: president,
    designation: "President",
    name: "DR. Hasmukh Vaidhya",
    place: "",
    mobile: "9825199252",
    state: "Gujarat",
  },
  {
    image: president,
    designation: "Gen. Secretry",
    name: "DR. K.L. Koradia",
    place: "",
    mobile: "9328507000",
    state: "Gujarat",
  },
  {
    image: president,
    designation: "Treasurer",
    name: "DR. Nitin B. Pathak",
    place: "",
    mobile: "9825944491",
    state: "Gujarat",
  },
  {
    image: president,
    designation: "President",
    name: "DR. Shashi Bhushan Madan",
    place: "Karmal",
    mobile: "9896788275",
    state: "Haryana",
  },
  {
    image: president,
    designation: "Gen. Secretry",
    name: "DR. Dinesh Chandra",
    place: "Kurukshetra",
    mobile: "9416266553",
    state: "Haryana",
  },
  {
    image: president,
    designation: "Treasurer",
    name: "DR. Rushipal Agarwal",
    place: "Ambala",
    mobile: "9416234560",
    state: "Haryana",
  },
  {
    image: president,
    designation: "President",
    name: "DR. Bhusanurmath R. G",
    place: "Bengaluru",
    mobile: "9448746389",
    state: "Karnataka",
  },
  {
    image: president,
    designation: "Gen. Secretry",
    name: "DR. KALLESH D MURASHILLIN",
    place: "Gadag",
    mobile: "9743014554",
    state: "Karnataka",
  },
  {
    image: president,
    designation: "Treasurer",
    name: "DR. S. S. Narayanapur",
    place: "Gadag",
    mobile: "9448829559",
    state: "Karnataka",
  },
  {
    image: president,
    designation: "President",
    name: "DR. Parvinder Bajaj",
    place: "Jalandhar",
    mobile: "9814509480",
    state: "Punjab",
  },
  {
    image: president,
    designation: "Gen. Secretry",
    name: "DR. I.P. Singh Sethi",
    place: "Jalandhar",
    mobile: "9814133344",
    state: "Punjab",
  },
  {
    image: president,
    designation: "Treasurer",
    name: "DR. Vipul Kakkar",
    place: "Gadag",
    mobile: "7508593445",
    state: "Punjab",
  },
];
